name: Build LaTeX document

on:
  push:
    branches:
      - compte_rendu
  pull_request:
    branches:
      - compte_rendu

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: rapport.tex
          latexmk_shell_escape: true
